### ISSUE TITLE
architecture.md images 

### ISSUE THREAD

**Issue by leederacola** [IUS-CS/TeamComputer#10]
maybe one of you can figure what dumb thing im doing to not get images working?

**Comment by gkute** [comment]
I'm not entirely sure myself.

**Comment by gkute** [comment]
Format: ![Alt Text](url) is the format that I found for it but not sure if that helps.

**Comment by gkute** [comment]
Format: '![Alt Text](url)'

**Comment by gkute** [comment]
Format:         ![Alt Text](url)

**Comment by gkute** [comment]
https://guides.github.com/features/mastering-markdown/

That site gives an example of how to do images if that helps.

**Comment by davdevor** [comment]
i got it fixed
